# 异常处理

> 原文：<https://www.learnpython.org/en/Exception_Handling>

* * *

编程时，会发生错误。这只是生活的事实。也许用户输入了错误的信息。可能网络资源不可用。也许程序内存不足。或者程序员甚至可能犯了一个错误！

Python 对错误的解决方案是异常。您可能以前见过异常。

```py
print(a)

#error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined 
```

哎呀！忘记给“a”变量赋值。

但是有时你不想让异常完全停止程序。当出现异常时，您可能想要做一些特殊的事情。这是在 *try/except* 程序块中完成的。

这里有一个简单的例子:假设你正在遍历一个列表。您需要迭代 20 个数字，但是列表是由用户输入的，其中可能没有 20 个数字。到达列表末尾后，您只想将其余的数字解释为 0。你可以这样做:

```py
def do_stuff_with_number(n):
    print(n)

def catch_this():
    the_list = (1, 2, 3, 4, 5)

    for i in range(20):
        try:
            do_stuff_with_number(the_list[i])
        except IndexError: # Raised when accessing a non-existing index of a list
            do_stuff_with_number(0)

catch_this() 
```

好了，这并不难！你可以这样做，没有任何例外。关于处理异常的更多细节，只需看看 [Python 文档](http://docs.python.org/tutorial/errors.html#handling-exceptions)

## 练习

处理所有的异常！回想之前的课程来返回演员的姓氏。